name: iOS CI Minimal

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'Deployment Type'
        required: true
        default: 'testflight'
        type: choice
        options:
        - testflight
        - production

env:
  # Firebase Configuration
  EXPO_PUBLIC_FIREBASE_API_KEY: ${{ secrets.EXPO_PUBLIC_FIREBASE_API_KEY }}
  EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN }}
  EXPO_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.EXPO_PUBLIC_FIREBASE_DATABASE_URL }}
  EXPO_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_PROJECT_ID }}
  EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET }}
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  EXPO_PUBLIC_FIREBASE_APP_ID: ${{ secrets.EXPO_PUBLIC_FIREBASE_APP_ID }}
  
  # Google OAuth Configuration
  EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID }}
  EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}
  
  # API Configuration
  EXPO_PUBLIC_API_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_BASE_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  EXPO_PUBLIC_OPENAI_API_KEY: ${{ secrets.EXPO_PUBLIC_OPENAI_API_KEY }}
  
  # RevenueCat Configuration
  EXPO_PUBLIC_REVENUECAT_IOS_API_KEY: ${{ secrets.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY }}
  
  # Expo Configuration
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build-ios:
    name: Build iOS App (Manual)
    runs-on: [self-hosted, macOS, ARM64, xcode-15]
    timeout-minutes: 60
    steps:
      - name: 📁 Use local repository
        run: |
          echo "Using local repository copy..."
          cd /Users/adam/GitHub/getmaximumfitiosapp
          pwd
          git status
          git pull origin main || echo "Git pull failed, continuing with current state"

      - name: 🏗 Setup Node
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: 📦 Install JavaScript dependencies
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp
        run: npm ci

      - name: ✍️ Write GoogleService-Info.plist
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp
        run: |
          echo "$IOS_GOOGLE_SERVICE_PLIST_B64" | base64 --decode > ios/GetMaximumFit/GoogleService-Info.plist
        env:
          IOS_GOOGLE_SERVICE_PLIST_B64: ${{ secrets.IOS_GOOGLE_SERVICE_PLIST_B64 }}

      - name: 🔑 Setup App Store Connect API Key
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp
        run: |
          mkdir -p ios/fastlane/keys
          echo "$APP_STORE_CONNECT_API_KEY_CONTENT" | base64 --decode > ios/fastlane/keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}

      - name:  iOS deps
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp/ios
        run: |
          gem install bundler --no-document
          bundle install --jobs 4
          bundle exec pod install --repo-update

      - name: 🔑 Setup CI Keychain
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp
        run: |
          # Delete keychain if it exists to start fresh
          security delete-keychain ci-keys.keychain || true
          
          # Create new keychain
          security create-keychain -p "$CI_KEYCHAIN_PWD" ci-keys.keychain
          
          # Set keychain settings
          security set-keychain-settings -t 3600 -l ci-keys.keychain
          
          # Add to keychain search list
          security list-keychains -s ci-keys.keychain login.keychain
          
          # Set as default keychain
          security default-keychain -s ci-keys.keychain
          
          # Unlock keychain
          security unlock-keychain -p "$CI_KEYCHAIN_PWD" ci-keys.keychain
          
          echo "✅ CI keychain created and configured"
        env:
          CI_KEYCHAIN_PWD: ${{ secrets.CI_KEYCHAIN_PWD }}

      - name: 🧪 Test Match Configuration
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp/ios
        run: |
          echo "🔍 Testing Match password and git access..."
          
          # Configure git authentication using the authorization token
          echo "Setting up git authentication..."
          AUTH_STRING=$(echo "$MATCH_GIT_BASIC_AUTHORIZATION" | base64 --decode)
          USERNAME=$(echo "$AUTH_STRING" | cut -d: -f1)
          TOKEN=$(echo "$AUTH_STRING" | cut -d: -f2)
          
          # Configure git credentials for this session using multiple methods
          git config --global credential.helper store
          echo "https://$USERNAME:$TOKEN@github.com" > ~/.git-credentials
          
          # Also configure git to use the token for this specific repository
          git config --global url."https://$USERNAME:$TOKEN@github.com/".insteadOf "https://github.com/"
          
          # Test git access first
          echo "Testing git repository access..."
          git ls-remote "$MATCH_GIT_URL" > /dev/null && echo "✅ Git access successful" || echo "❌ Git access failed"
          
          # Test Match password - ensure MATCH_GIT_BASIC_AUTHORIZATION is available to Match
          echo "Testing Match password..."
          env MATCH_GIT_BASIC_AUTHORIZATION="$MATCH_GIT_BASIC_AUTHORIZATION" bundle exec fastlane match appstore --readonly || {
            echo "❌ Match test failed - checking details..."
            echo "Git URL: $MATCH_GIT_URL"
            echo "Match password length: ${#MATCH_PASSWORD}"
            exit 1
          }
          
          # Clean up credentials
          rm -f ~/.git-credentials
          git config --global --unset credential.helper
          git config --global --unset url."https://$USERNAME:$TOKEN@github.com/".insteadOf
          
          echo "✅ Match configuration test passed!"
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

      - name: 🍎 Fastlane Beta
        working-directory: /Users/adam/GitHub/getmaximumfitiosapp/ios
        env:
          ASC_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          ASC_KEY_PATH: "./fastlane/keys/AuthKey_${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}.p8"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          CI_KEYCHAIN_PWD: ${{ secrets.CI_KEYCHAIN_PWD }}
          GIT_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          # Set up git authentication for Match
          AUTH_STRING=$(echo "$MATCH_GIT_BASIC_AUTHORIZATION" | base64 --decode)
          USERNAME=$(echo "$AUTH_STRING" | cut -d: -f1)
          TOKEN=$(echo "$AUTH_STRING" | cut -d: -f2)
          git config --global credential.helper store
          echo "https://$USERNAME:$TOKEN@github.com" > ~/.git-credentials
          git config --global url."https://$USERNAME:$TOKEN@github.com/".insteadOf "https://github.com/"
          
          # Run Fastlane
          bundle exec fastlane beta
          
          # Clean up
          rm -f ~/.git-credentials
          git config --global --unset credential.helper || true
          git config --global --unset url."https://$USERNAME:$TOKEN@github.com/".insteadOf || true
